name: CI

on:
  push:
    branches: ['main']
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.prisma'
      - '.github/workflows/ci.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.prisma'
      - '.github/workflows/ci.yml'

env:
  NEXT_PUBLIC_WEB_URL: http://localhost:3000
  NEXT_PUBLIC_API_URL: http://localhost:3001
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: ci-test-secret
  AUTH_RESEND_EMAIL: ci@test.com
  POSTGRES_PRISMA_URL: postgresql://postgres:postgres@localhost:5432/playmoney?schema=public
  POSTGRES_URL_NON_POOLING: postgresql://postgres:postgres@localhost:5432/playmoney?schema=public

jobs:
  checks:
    name: Lint, type-check, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Run format
        run: npm run format

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test
